# Generated by Django 5.2.8 on 2025-11-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('std', models.CharField(max_length=50)),
                ('section', models.CharField(choices=[('computer science', 'Computer Science'), ('others', 'Others'), ('biology', 'Biology'), ('accounts', 'Accounts')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='students/')),
            ],
        ),
    ]
