# Generated by Django 5.2.8 on 2025-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.CharField(choices=[('accounts', 'Accounts'), ('others', 'Others'), ('computer science', 'Computer Science'), ('biology', 'Biology')], max_length=50),
        ),
    ]
